/**
 * @lifeos/contracts
 *
 * Shared contracts for SDK/mobile surfaces and the Personal Operations hero loop.
 */

export { Topics } from './topics';

export { LoginRequestSchema, type LoginRequest, type AuthTokens, type UserProfile } from './auth';

export {
  CaptureTypeSchema,
  CaptureRequestSchema,
  CaptureStatusSchema,
  CaptureResultSchema,
  CaptureListItemSchema,
  type CaptureType,
  type CaptureRequest,
  type CaptureRequestMetadata,
  type CaptureStatus,
  type CaptureResult,
  type CaptureListItem,
} from './capture';

export {
  HouseholdRoleSchema,
  HouseholdMemberStatusSchema,
  ChoreStatusSchema,
  ShoppingItemStatusSchema,
  HouseholdCreateRequestSchema,
  HouseholdInviteMemberRequestSchema,
  HouseholdJoinRequestSchema,
  HouseholdChangeMemberRoleRequestSchema,
  HouseholdAddShoppingItemRequestSchema,
  HouseholdUpdateShoppingItemStatusRequestSchema,
  HouseholdCreateChoreRequestSchema,
  HouseholdCreateReminderRequestSchema,
  HouseholdCreateNoteRequestSchema,
  HouseholdMemberInvitedSchema,
  HouseholdMemberJoinedSchema,
  HouseholdMemberRoleChangedSchema,
  HouseholdChoreAssignedSchema,
  HouseholdChoreCompletedSchema,
  HouseholdShoppingItemAddedSchema,
  HouseholdShoppingItemPurchasedSchema,
  HouseholdCalendarEventCreatedSchema,
  HouseholdVoiceCaptureCreatedSchema,
  HomeNodeVoiceSessionStartedSchema,
  HomeNodeVoiceSessionCompletedSchema,
  HomeNodeVoiceSessionFailedSchema,
  HouseholdShoppingItemAddRequestedSchema,
  HouseholdChoreCreateRequestedSchema,
  HouseholdReminderCreateRequestedSchema,
  HouseholdNoteCreateRequestedSchema,
  HouseholdCaptureUnresolvedSchema,
  HouseholdAutomationFailedSchema,
  HouseholdCaptureStatusSchema,
  HouseholdCaptureStatusResponseSchema,
  HouseholdHomeStateChangedSchema,
  HouseholdHomeStateConfigSchema,
  HouseholdUpdateConfigRequestSchema,
  HouseholdHaWebhookRequestSchema,
  HomeStateChangeSchema,
  HouseholdContextSummarySchema,
  HouseholdReminderFiredSchema,
  AuditLogEntrySchema,
  type HouseholdRole,
  type HouseholdMemberStatus,
  type ChoreStatus,
  type ShoppingItemStatus,
  type HouseholdCreateRequest,
  type HouseholdInviteMemberRequest,
  type HouseholdJoinRequest,
  type HouseholdChangeMemberRoleRequest,
  type HouseholdAddShoppingItemRequest,
  type HouseholdUpdateShoppingItemStatusRequest,
  type HouseholdCreateChoreRequest,
  type HouseholdCreateReminderRequest,
  type HouseholdCreateNoteRequest,
  type HouseholdMemberInvited,
  type HouseholdMemberJoined,
  type HouseholdMemberRoleChanged,
  type HouseholdChoreAssigned,
  type HouseholdChoreCompleted,
  type HouseholdShoppingItemAdded,
  type HouseholdShoppingItemPurchased,
  type HouseholdCalendarEventCreated,
  type HouseholdVoiceCaptureCreated,
  type HomeNodeVoiceSessionStarted,
  type HomeNodeVoiceSessionCompleted,
  type HomeNodeVoiceSessionFailed,
  type HouseholdShoppingItemAddRequested,
  type HouseholdChoreCreateRequested,
  type HouseholdReminderCreateRequested,
  type HouseholdNoteCreateRequested,
  type HouseholdCaptureUnresolved,
  type HouseholdAutomationFailed,
  type HouseholdCaptureStatus,
  type HouseholdCaptureStatusResponse,
  type HouseholdHomeStateChanged,
  type HouseholdHomeStateConfig,
  type HouseholdUpdateConfigRequest,
  type HouseholdHaWebhookRequest,
  type HomeStateChange,
  type HouseholdContextSummary,
  type HouseholdReminderFired,
  type AuditLogEntry,
} from './household';

export {
  SurfaceKindSchema,
  SurfaceTrustLevelSchema,
  SurfaceCapabilitySchema,
  HomeNodeSurfaceSchema,
  HomeNodeZoneTypeSchema,
  HomeNodeZoneSchema,
  HomeNodeHomeSchema,
  HomeModeSchema,
  HomeStateSnapshotSchema,
  HomeNodeSurfaceRegisteredSchema,
  HomeNodeStateSnapshotUpdatedSchema,
  HomeNodeDisplayFeedEventSchema,
  HomeNodeDisplayFeedRequestSchema,
  HomeNodeDisplayEventItemSchema,
  HomeNodeDisplayChoreItemSchema,
  HomeNodeDisplayShoppingItemSchema,
  HomeNodeDisplayReminderItemSchema,
  HomeNodeDisplayNoticeItemSchema,
  HomeNodeDisplayFeedSchema,
  type SurfaceKind,
  type SurfaceTrustLevel,
  type SurfaceCapability,
  type HomeNodeSurface,
  type HomeNodeZoneType,
  type HomeNodeZone,
  type HomeNodeHome,
  type HomeMode,
  type HomeStateSnapshot,
  type HomeNodeSurfaceRegistered,
  type HomeNodeStateSnapshotUpdated,
  type HomeNodeDisplayFeedEvent,
  type HomeNodeDisplayFeedRequest,
  type HomeNodeDisplayEventItem,
  type HomeNodeDisplayChoreItem,
  type HomeNodeDisplayShoppingItem,
  type HomeNodeDisplayReminderItem,
  type HomeNodeDisplayNoticeItem,
  type HomeNodeDisplayFeed,
} from './household';

export {
  ApprovalRequestSchema,
  ApprovalResultSchema,
  InboxItemTypeSchema,
  ReminderInboxPayloadSchema,
  InboxItemDataSchema,
  InboxItemSchema,
  InboxActionRequestSchema,
  ReviewCloseDayRequestSchema,
  type ApprovalRequest,
  type ApprovalResult,
  type InboxItemType,
  type ReminderInboxPayload,
  type InboxItemData,
  type InboxItem,
  type InboxActionRequest,
  type ReviewCloseDayRequest,
} from './inbox';

export {
  PlanPrioritySchema,
  PlanTaskStatusSchema,
  PlanTaskSchema,
  PlanSchema,
  PlanningSuggestionSchema,
  PlanBlockedRequestSchema,
  PlanAlternativesResponseSchema,
  type PlanPriority,
  type PlanTaskStatus,
  type PlanTask,
  type Plan,
  type PlanningSuggestion,
  type PlanBlockedRequest,
  type PlanAlternativesResponse,
} from './plan';

export {
  ReminderStatusSchema,
  ReminderChannelSchema,
  ReminderSchema,
  type ReminderStatus,
  type ReminderChannel,
  type Reminder,
} from './reminder';

export {
  ReviewPeriodSchema,
  ReviewSourceSchema,
  ReviewLoopSummarySchema,
  ReviewPayloadSchema,
  ReviewReportSchema,
  type ReviewPeriod,
  type ReviewSource,
  type ReviewLoopSummary,
  type ReviewPayload,
  type ReviewReport,
} from './review';

export { HeroLoopEventSchema, type HeroLoopEvent } from './events';

export {
  CaptureCreateRequestSchema,
  CaptureCreateResponseSchema,
  InboxListResponseSchema,
  PlanCreateRequestSchema,
  PlanCreateResponseSchema,
  ReminderScheduleRequestSchema,
  ReminderScheduleResponseSchema,
  ReviewGenerateRequestSchema,
  ReviewGenerateResponseSchema,
  ApiErrorResponseSchema,
  type CaptureCreateRequest,
  type CaptureCreateResponse,
  type InboxListResponse,
  type PlanCreateRequest,
  type PlanCreateResponse,
  type ReminderScheduleRequest,
  type ReminderScheduleResponse,
  type ReviewGenerateRequest,
  type ReviewGenerateResponse,
  type ApiErrorResponse,
} from './api';

export {
  HeroLoopEntitySchemas,
  type HeroLoopEntitySchemaMap,
  type HeroLoopEntityName,
  type HeroLoopEntityValue,
} from './entities';

export { type TimelineEntry, type GoalSummary } from './timeline';

export {
  type PushTokenRegistration,
  type NotificationPayload,
  type NotificationRoute,
} from './notifications';

export { type DeviceInfo, type RevokeDeviceRequest } from './devices';

export {
  KnownLifeOSErrorCodeSchema,
  LifeOSErrorSchema,
  type KnownLifeOSErrorCode,
  type LifeOSError,
} from './errors';

export {
  HealthCheckKeySchema,
  HealthCheckStatusSchema,
  RepairActionSchema,
  HealthCheckResultSchema,
  UXPreferencesSchema,
  OnboardingStageSchema,
  OnboardingProgressSchema,
  TourProgressSchema,
  AssistantProfileInputSchema,
  AssistantProfileSchema,
  type HealthCheckKey,
  type HealthCheckStatus,
  type RepairAction,
  type HealthCheckResult,
  type UXPreferences,
  type OnboardingStage,
  type OnboardingProgress,
  type TourProgress,
  type AssistantProfileInput,
  type AssistantProfile,
} from './ux';

export type { SDKConfig } from './sdk';

export * from './loop/index';
