/**
 * Canonical NATS topic names shared across all LifeOS packages.
 *
 * Defined here (in contracts) so that mobile and other client packages can
 * import topic names without pulling in the server-side NATS runtime from
 * @lifeos/event-bus.
 */
export const Topics = {
  person: {
    created: 'person.created',
    updated: 'person.updated',
  },
  health: {
    changed: 'health.changed',
    checkRequested: 'health.check.requested',
  },
  production: {
    taskCreated: 'production.task.created',
    taskCompleted: 'production.task.completed',
  },
  goal: {
    proposed: 'goal.proposed',
    updated: 'goal.updated',
  },
  plan: {
    created: 'plan.created',
    revised: 'plan.revised',
  },
  task: {
    scheduled: 'task.scheduled',
    statusChanged: 'task.status.changed',
  },
  module: {
    loaded: 'module.loaded',
    failed: 'module.failed',
  },
  device: {
    stateChanged: 'device.state.changed',
    commandIssued: 'device.command.issued',
  },
  automation: {
    triggerFired: 'automation.trigger.fired',
    actionExecuted: 'automation.action.executed',
  },
  agent: {
    workRequested: 'agent.work.requested',
    workCompleted: 'agent.work.completed',
  },
  lifeos: {
    tickOverdue: 'lifeos.tick.overdue',
    taskCompleted: 'lifeos.task.completed',
    reminderScheduled: 'lifeos.reminder.scheduled',
    reminderFired: 'lifeos.reminder.fired',
    reminderFollowupCreated: 'lifeos.reminder.followup.created',
    voiceWakeDetected: 'lifeos.voice.wake.detected',
    voiceCommandReceived: 'lifeos.voice.command.received',
    voiceCommandProcessed: 'lifeos.voice.command.processed',
    voiceCommandUnhandled: 'lifeos.voice.command.unhandled',
    voiceIntentCalendarAdd: 'lifeos.voice.intent.calendar.add',
    voiceIntentTaskAdd: 'lifeos.voice.intent.task.add',
    voiceIntentResearch: 'lifeos.voice.intent.research',
    voiceIntentNoteAdd: 'lifeos.voice.intent.note.add',
    voiceIntentNoteSearch: 'lifeos.voice.intent.note.search',
    voiceIntentWeather: 'lifeos.voice.intent.weather',
    voiceIntentNews: 'lifeos.voice.intent.news',
    voiceIntentEmailSummarize: 'lifeos.voice.intent.email.summarize',
    voiceIntentBriefing: 'lifeos.voice.intent.briefing',
    voiceIntentPreferenceSet: 'lifeos.voice.intent.preference.set',
    voiceIntentHealthLog: 'lifeos.voice.intent.health.log',
    voiceIntentHealthQuery: 'lifeos.voice.intent.health.query',
    voiceIntentHabitCreate: 'lifeos.voice.intent.habit.create',
    voiceIntentHabitCheckin: 'lifeos.voice.intent.habit.checkin',
    voiceIntentHabitStatus: 'lifeos.voice.intent.habit.status',
    calendarEventAdded: 'lifeos.calendar.event.added',
    taskRescheduleSuggested: 'lifeos.task.reschedule.suggested',
    noteAdded: 'lifeos.note.added',
    noteSearchCompleted: 'lifeos.note.search.completed',
    researchCompleted: 'lifeos.research.completed',
    weatherSnapshotCaptured: 'lifeos.weather.snapshot.captured',
    healthMetricLogged: 'lifeos.health.metric.logged',
    healthStreakUpdated: 'lifeos.health.streak.updated',
    habitCheckinRecorded: 'lifeos.habit.checkin.recorded',
    habitStreakMilestone: 'lifeos.habit.streak.milestone',
    planningAssistantTaskPlanned: 'lifeos.planning-assistant.task.planned',
    planningAssistantReminderScheduled: 'lifeos.planning-assistant.reminder.scheduled',
    planningAssistantPlanUpdated: 'lifeos.planning-assistant.plan.updated',
    notificationBridgeSent: 'lifeos.notification-bridge.sent',
    notificationBridgeFailed: 'lifeos.notification-bridge.failed',
    newsDigestReady: 'lifeos.news.digest.ready',
    emailDigestReady: 'lifeos.email.digest.ready',
    orchestratorSuggestion: 'lifeos.orchestrator.suggestion',
    briefingGenerated: 'lifeos.briefing.generated',
    personalityUpdated: 'lifeos.personality.updated',
    memoryStatusGenerated: 'lifeos.memory.status.generated',
    syncDelta: 'lifeos.sync.delta',
    syncAuditLogged: 'lifeos.sync.audit.logged',
    syncConflictDetected: 'lifeos.sync.conflict.detected',
    syncDevicePaired: 'lifeos.sync.device.paired',
    syncDevicesListed: 'lifeos.sync.devices.listed',
    syncDemoCompleted: 'lifeos.sync.demo.completed',
    meshNodeHeartbeat: 'lifeos.mesh.node.heartbeat',
    meshNodeLeft: 'lifeos.mesh.node.left',
    meshLeaderElected: 'lifeos.mesh.leader.elected',
    meshLeaderChanged: 'lifeos.mesh.leader.changed',
    meshLeaderLost: 'lifeos.mesh.leader.lost',
    meshDelegateRequested: 'lifeos.mesh.delegate.requested',
    meshDelegateAccepted: 'lifeos.mesh.delegate.accepted',
    meshDelegateCompleted: 'lifeos.mesh.delegate.completed',
    meshDelegateFailed: 'lifeos.mesh.delegate.failed',
    meshDelegateFallbackLocal: 'lifeos.mesh.delegate.fallback_local',
    securityPolicyDenied: 'lifeos.security.policy.denied',
    securityAuthFailed: 'lifeos.security.auth.failed',
    trustExplanationLogged: 'lifeos.trust.explanation.logged',
    householdMemberInvited: 'lifeos.household.member.invited',
    householdMemberJoined: 'lifeos.household.member.joined',
    householdMemberRoleChanged: 'lifeos.household.member.role.changed',
    householdChoreAssigned: 'lifeos.household.chore.assigned',
    householdChoreCompleted: 'lifeos.household.chore.completed',
    householdShoppingItemAdded: 'lifeos.household.shopping.item.added',
    householdShoppingItemPurchased: 'lifeos.household.shopping.item.purchased',
    householdCalendarEventCreated: 'lifeos.household.calendar.event.created',
    householdReminderFired: 'lifeos.household.reminder.fired',
    householdHomeStateChanged: 'lifeos.household.homestate.changed',
    householdVoiceCaptureCreated: 'lifeos.household.voice.capture.created',
    householdShoppingItemAddRequested: 'lifeos.household.shopping.item.add.requested',
    householdChoreCreateRequested: 'lifeos.household.chore.create.requested',
    householdReminderCreateRequested: 'lifeos.household.reminder.create.requested',
    householdNoteCreateRequested: 'lifeos.household.note.create.requested',
    householdCaptureUnresolved: 'lifeos.household.capture.unresolved',
    householdAutomationFailed: 'lifeos.household.automation.failed',
    homeNodeSurfaceRegistered: 'lifeos.homenode.surface.registered',
    homeNodeSurfaceDeregistered: 'lifeos.homenode.surface.deregistered',
    homeNodeStateSnapshotUpdated: 'lifeos.homenode.state.snapshot.updated',
    homeNodeDisplayFeedUpdated: 'lifeos.homenode.display.feed.updated',
    homeNodeVoiceSessionStarted: 'lifeos.homenode.voice.session.started',
    homeNodeVoiceSessionCompleted: 'lifeos.homenode.voice.session.completed',
    homeNodeVoiceSessionFailed: 'lifeos.homenode.voice.session.failed',
    homeNodeHealthChanged: 'lifeos.homenode.health.changed',
    captureRecorded: 'lifeos.capture.recorded',
    inboxTriaged: 'lifeos.inbox.triaged',
  },
} as const;
