import { invoke } from '@tauri-apps/api/core';

export interface GraphSummary {
  totalGoals: number;
  totalPlans: number;
  activeGoals?: Array<{ id: string; title?: string; completedTasks?: number; totalTasks?: number }>;
  updatedAt?: string;
}

export interface GoalPlanTask {
  title: string;
  dueDate?: string;
  priority?: number;
}

export interface GoalPlan {
  title?: string;
  summary?: string;
  tasks?: GoalPlanTask[];
  deadline?: string;
}

export interface ModuleRow {
  id: string;
  tier: string;
  enabled: boolean;
  available: boolean;
  subFeatures: string[];
}

export interface MarketplaceEntry {
  id: string;
  repo: string;
  description: string;
  category: string;
  resourceHint: string;
  certified: boolean;
  installed: boolean;
}

export interface LifeOsSettings {
  model: string;
  ollamaHost: string;
  natsUrl: string;
  voiceEnabled: boolean;
}

interface SidecarResponse<T> {
  result?: T;
  error?: string;
}

function isTauriRuntime(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

async function invokeOrMock<T>(command: string, payload?: Record<string, unknown>): Promise<T> {
  if (isTauriRuntime()) {
    return invoke<T>(command, payload);
  }
  return mockInvoke<T>(command, payload);
}

function mockInvoke<T>(command: string, payload?: Record<string, unknown>): T {
  if (command === 'graph_summary') {
    return {
      totalGoals: 2,
      totalPlans: 2,
      activeGoals: [
        { id: 'goal-1', title: 'Board meeting prep', completedTasks: 2, totalTasks: 5 },
        { id: 'goal-2', title: 'Q1 planning', completedTasks: 0, totalTasks: 3 },
      ],
    } as T;
  }

  if (command === 'goal_run') {
    return {
      title: String(payload?.goal ?? 'Generated plan'),
      summary: 'A starter plan generated by the LifeOS goal engine.',
      deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      tasks: [
        { title: 'Draft key outcomes', dueDate: 'tomorrow', priority: 5 },
        { title: 'Create timeline', dueDate: 'this week', priority: 4 },
        { title: 'Share progress update', dueDate: 'this week', priority: 3 },
      ],
    } as T;
  }

  if (command === 'task_list') {
    return [
      { id: 'task-1', title: 'Prepare board slides', dueDate: 'Fri', status: 'open' },
      { id: 'task-2', title: 'Review Q1 budget', dueDate: 'Overdue', status: 'open' },
      { id: 'task-3', title: 'Send team update', dueDate: 'Today', status: 'open' },
    ] as T;
  }

  if (command === 'modules_list') {
    return [
      { id: 'scheduler', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'notes', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'calendar', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'research', tier: 'optional', enabled: false, available: true, subFeatures: [] },
    ] as T;
  }

  if (command === 'marketplace_list') {
    return [
      {
        id: 'research',
        repo: 'lifeos/research',
        description: 'Research assistant with local context and follow-up memory.',
        category: 'assistant',
        resourceHint: 'High CPU',
        certified: true,
        installed: true,
      },
      {
        id: 'weather',
        repo: 'lifeos/weather',
        description: 'Offline-first weather snapshots and spoken forecasts.',
        category: 'utility',
        resourceHint: 'Low CPU',
        certified: true,
        installed: false,
      },
    ] as T;
  }

  if (command === 'settings_read') {
    return {
      model: 'llama3.1:8b',
      ollamaHost: 'http://127.0.0.1:11434',
      natsUrl: 'nats://127.0.0.1:4222',
      voiceEnabled: true,
    } as T;
  }

  if (command === 'settings_write') {
    return {
      model: String(payload?.model ?? 'llama3.1:8b'),
      ollamaHost: String(payload?.ollamaHost ?? 'http://127.0.0.1:11434'),
      natsUrl: String(payload?.natsUrl ?? 'nats://127.0.0.1:4222'),
      voiceEnabled: Boolean(payload?.voiceEnabled ?? true),
    } as T;
  }

  throw new Error(`No mock available for command: ${command}`);
}

export async function getGraphSummary(): Promise<GraphSummary> {
  return invokeOrMock<GraphSummary>('graph_summary');
}

export async function runGoal(goal: string, model: string): Promise<GoalPlan> {
  return invokeOrMock<GoalPlan>('goal_run', { goal, model });
}

export async function listTasks(): Promise<Array<{ id: string; title: string; dueDate?: string }>> {
  return invokeOrMock<Array<{ id: string; title: string; dueDate?: string }>>('task_list');
}

export async function completeTask(taskId: string): Promise<SidecarResponse<{ taskId: string }>> {
  return invokeOrMock<SidecarResponse<{ taskId: string }>>('task_complete', { taskId });
}

export async function listModules(): Promise<ModuleRow[]> {
  return invokeOrMock<ModuleRow[]>('modules_list');
}

export async function enableModule(id: string): Promise<SidecarResponse<{ id: string }>> {
  return invokeOrMock<SidecarResponse<{ id: string }>>('module_enable', { id });
}

export async function disableModule(id: string): Promise<SidecarResponse<{ id: string }>> {
  return invokeOrMock<SidecarResponse<{ id: string }>>('module_disable', { id });
}

export async function listMarketplace(certifiedOnly = false): Promise<MarketplaceEntry[]> {
  return invokeOrMock<MarketplaceEntry[]>('marketplace_list', { certifiedOnly });
}

export async function readSettings(): Promise<LifeOsSettings> {
  return invokeOrMock<LifeOsSettings>('settings_read');
}

export async function writeSettings(next: Partial<LifeOsSettings>): Promise<LifeOsSettings> {
  return invokeOrMock<LifeOsSettings>('settings_write', next);
}
