import { invoke } from '@tauri-apps/api/core';
import type { InboxItem } from '@lifeos/contracts';

export interface GraphSummary {
  totalGoals: number;
  totalPlans: number;
  activeGoals?: Array<{ id: string; title?: string; completedTasks?: number; totalTasks?: number }>;
  goalLinks?: Array<{
    source?: string;
    target?: string;
    sourceId?: string;
    targetId?: string;
    relation?: string;
    relationship?: string;
    type?: string;
  }>;
  relationships?: Array<{
    source?: string;
    target?: string;
    sourceId?: string;
    targetId?: string;
    relation?: string;
    relationship?: string;
    type?: string;
  }>;
  updatedAt?: string;
}

export interface GoalPlanTask {
  title: string;
  dueDate?: string;
  priority?: number;
}

export interface GoalPlan {
  title?: string;
  summary?: string;
  tasks?: GoalPlanTask[];
  deadline?: string;
}

export interface ReviewLoopSummary {
  pendingCaptures: number;
  actionsDueToday: number;
  unacknowledgedReminders: number;
  completedActions: string[];
  suggestedNextActions?: string[];
}

export interface CaptureInput {
  text: string;
}

export interface ModuleRow {
  id: string;
  tier: string;
  enabled: boolean;
  available: boolean;
  subFeatures: string[];
  permissions?: {
    graph: string[];
    voice: string[];
    network: string[];
    events: string[];
  };
}

export interface MarketplaceEntry {
  id: string;
  repo: string;
  description: string;
  category: string;
  resourceHint: string;
  certified: boolean;
  installed: boolean;
}

export interface LifeOsSettings {
  model: string;
  ollamaHost: string;
  natsUrl: string;
  voiceEnabled: boolean;
  localOnlyMode: boolean;
  cloudAssistEnabled: boolean;
  trustAuditEnabled: boolean;
  transparencyTipsEnabled: boolean;
}

export interface TrustModuleSummary {
  id: string;
  tier: 'core' | 'optional';
  enabled: boolean;
  available: boolean;
  permissions: {
    graph: string[];
    voice: string[];
    network: string[];
    events: string[];
  };
}

export interface TrustStatus {
  generatedAt: string;
  ownership: {
    dataOwnership: string;
    methodsTransparency: string;
    localFirstDefault: boolean;
    cloudAssistEnabled: boolean;
  };
  runtime: {
    model: string;
    ollamaHost: string;
    natsUrl: string;
    localOnlyMode: boolean;
    trustAuditEnabled: boolean;
    policyEnforced: boolean;
    moduleManifestRequired: boolean;
    moduleRuntimePermissions: string;
  };
  modules: TrustModuleSummary[];
  recentDecisions: Array<{
    at: string;
    category: 'ownership' | 'policy' | 'runtime';
    message: string;
  }>;
}

interface SidecarResponse<T> {
  result?: T;
  error?: string;
}

export function isTauriRuntime(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

export function isMockRuntime(): boolean {
  return !isTauriRuntime();
}

async function invokeOrMock<T>(command: string, payload?: Record<string, unknown>): Promise<T> {
  if (isTauriRuntime()) {
    return invoke<T>(command, payload);
  }
  return mockInvoke<T>(command, payload);
}

function mockInvoke<T>(command: string, payload?: Record<string, unknown>): T {
  if (command === 'graph_summary') {
    return {
      totalGoals: 2,
      totalPlans: 2,
      activeGoals: [
        { id: 'goal-1', title: 'Board meeting prep', completedTasks: 2, totalTasks: 5 },
        { id: 'goal-2', title: 'Q1 planning', completedTasks: 0, totalTasks: 3 },
      ],
    } as T;
  }

  if (command === 'goal_run') {
    return {
      title: String(payload?.goal ?? 'Generated plan'),
      summary: 'A starter plan generated by the LifeOS goal engine.',
      deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      tasks: [
        { title: 'Draft key outcomes', dueDate: 'tomorrow', priority: 5 },
        { title: 'Create timeline', dueDate: 'this week', priority: 4 },
        { title: 'Share progress update', dueDate: 'this week', priority: 3 },
      ],
    } as T;
  }

  if (command === 'task_list') {
    return [
      { id: 'task-1', title: 'Prepare board slides', dueDate: 'Fri', status: 'open' },
      { id: 'task-2', title: 'Review Q1 budget', dueDate: 'Overdue', status: 'open' },
      { id: 'task-3', title: 'Send team update', dueDate: 'Today', status: 'open' },
    ] as T;
  }

  if (command === 'modules_list') {
    return [
      { id: 'scheduler', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'notes', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'calendar', tier: 'core', enabled: true, available: true, subFeatures: [] },
      { id: 'research', tier: 'optional', enabled: false, available: true, subFeatures: [] },
    ] as T;
  }

  if (command === 'marketplace_list') {
    return [
      {
        id: 'research',
        repo: 'lifeos/research',
        description: 'Research assistant with local context and follow-up memory.',
        category: 'assistant',
        resourceHint: 'High CPU',
        certified: true,
        installed: true,
      },
      {
        id: 'weather',
        repo: 'lifeos/weather',
        description: 'Offline-first weather snapshots and spoken forecasts.',
        category: 'utility',
        resourceHint: 'Low CPU',
        certified: true,
        installed: false,
      },
    ] as T;
  }

  if (command === 'settings_read') {
    return {
      model: 'llama3.1:8b',
      ollamaHost: 'http://127.0.0.1:11434',
      natsUrl: 'nats://127.0.0.1:4222',
      voiceEnabled: true,
      localOnlyMode: true,
      cloudAssistEnabled: false,
      trustAuditEnabled: true,
      transparencyTipsEnabled: true,
    } as T;
  }

  if (command === 'settings_write') {
    return {
      model: String(payload?.model ?? 'llama3.1:8b'),
      ollamaHost: String(payload?.ollamaHost ?? 'http://127.0.0.1:11434'),
      natsUrl: String(payload?.natsUrl ?? 'nats://127.0.0.1:4222'),
      voiceEnabled: Boolean(payload?.voiceEnabled ?? true),
      localOnlyMode: Boolean(payload?.localOnlyMode ?? true),
      cloudAssistEnabled: Boolean(payload?.cloudAssistEnabled ?? false),
      trustAuditEnabled: Boolean(payload?.trustAuditEnabled ?? true),
      transparencyTipsEnabled: Boolean(payload?.transparencyTipsEnabled ?? true),
    } as T;
  }

  if (command === 'settings_models') {
    return { models: ['llama3.1:8b', 'qwen3:8b'] } as T;
  }

  if (command === 'trust_status') {
    return {
      generatedAt: new Date().toISOString(),
      ownership: {
        dataOwnership: 'Your data is yours. LifeOS keeps your graph and settings on your machine by default.',
        methodsTransparency: 'Every major action is inspectable through commands, manifests, and event traces.',
        localFirstDefault: true,
        cloudAssistEnabled: false,
      },
      runtime: {
        model: 'llama3.1:8b',
        ollamaHost: 'http://127.0.0.1:11434',
        natsUrl: 'nats://127.0.0.1:4222',
        localOnlyMode: true,
        trustAuditEnabled: true,
        policyEnforced: true,
        moduleManifestRequired: true,
        moduleRuntimePermissions: 'strict',
      },
      modules: [],
      recentDecisions: [],
    } as T;
  }

  if (command === 'task_complete') {
    const taskId = payload?.taskId;
    return { id: taskId, status: 'done' } as T;
  }

  if (command === 'capture_create') {
    return { id: 'mock-capture-' + Date.now() } as T;
  }

  if (command === 'inbox_list') {
    return [
      {
        id: 'inbox-1',
        title: 'Idea: turn garage cleanout into a weekend project plan',
        type: 'capture',
        source: 'typed',
        createdAt: Date.now() - 8 * 60 * 1000,
        read: false,
        description: 'Captured from quick entry.',
        data: {},
      },
      {
        id: 'inbox-2',
        title: 'Reminder: follow up with dentist office',
        type: 'reminder',
        source: 'voice',
        createdAt: Date.now() - 2 * 60 * 60 * 1000,
        read: false,
        description: 'Voice capture from commute.',
        data: {},
      },
      {
        id: 'inbox-3',
        title: 'School calendar sync completed',
        type: 'notification',
        source: 'notification',
        createdAt: Date.now() - 28 * 60 * 60 * 1000,
        read: false,
        description: 'Bridge service pushed a status update.',
        data: {},
      },
    ] as T;
  }

  if (command === 'task_create') {
    return { id: 'mock-task-' + Date.now() } as T;
  }

  if (command === 'reminder_schedule') {
    return { id: 'mock-reminder-' + Date.now() } as T;
  }

  if (command === 'review_daily') {
    return {
      pendingCaptures: 1,
      actionsDueToday: 2,
      unacknowledgedReminders: 2,
      completedActions: [],
    } as T;
  }

  throw new Error(`No mock available for command: ${command}`);
}

export async function getGraphSummary(): Promise<GraphSummary> {
  return invokeOrMock<GraphSummary>('graph_summary');
}

export async function runGoal(goal: string, model: string): Promise<GoalPlan> {
  return invokeOrMock<GoalPlan>('goal_run', { goal, model });
}

export async function listTasks(): Promise<Array<{ id: string; title: string; dueDate?: string }>> {
  return invokeOrMock<Array<{ id: string; title: string; dueDate?: string }>>('task_list');
}

export async function completeTask(taskId: string): Promise<SidecarResponse<{ taskId: string }>> {
  return invokeOrMock<SidecarResponse<{ taskId: string }>>('task_complete', { taskId });
}

export async function getDailyReview(): Promise<ReviewLoopSummary> {
  return invokeOrMock<ReviewLoopSummary>('review_daily');
}

export async function completeAction(actionId: string): Promise<void> {
  await completeTask(actionId);
}

export async function listModules(): Promise<ModuleRow[]> {
  return invokeOrMock<ModuleRow[]>('modules_list');
}

export async function enableModule(id: string): Promise<SidecarResponse<{ id: string }>> {
  return invokeOrMock<SidecarResponse<{ id: string }>>('module_enable', { id });
}

export async function disableModule(id: string): Promise<SidecarResponse<{ id: string }>> {
  return invokeOrMock<SidecarResponse<{ id: string }>>('module_disable', { id });
}

export async function listMarketplace(certifiedOnly = false): Promise<MarketplaceEntry[]> {
  return invokeOrMock<MarketplaceEntry[]>('marketplace_list', { certifiedOnly });
}

export async function readSettings(): Promise<LifeOsSettings> {
  return invokeOrMock<LifeOsSettings>('settings_read');
}

export async function writeSettings(next: Partial<LifeOsSettings>): Promise<LifeOsSettings> {
  return invokeOrMock<LifeOsSettings>('settings_write', next);
}

export async function listOllamaModels(): Promise<string[]> {
  const result = await invokeOrMock<{ models?: unknown }>('settings_models');
  if (!result || !Array.isArray(result.models)) {
    return [];
  }

  return result.models
    .map((item) => String(item ?? '').trim())
    .filter((item) => item.length > 0);
}

export async function readTrustStatus(): Promise<TrustStatus> {
  return invokeOrMock<TrustStatus>('trust_status');
}

export async function createCapture(text: string): Promise<{ id: string }> {
  return invokeOrMock<{ id: string }>('capture_create', { text });
}

export async function listInboxItems(): Promise<InboxItem[]> {
  return invokeOrMock<InboxItem[]>('inbox_list');
}

export async function createTask(captureId: string, title: string): Promise<{ id: string }> {
  return invokeOrMock<{ id: string }>('task_create', { captureId, title });
}

export async function scheduleReminder(captureId: string, title: string): Promise<{ id: string }> {
  return invokeOrMock<{ id: string }>('reminder_schedule', { captureId, title });
}
