CREATE TABLE goal_engine.goals (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  status TEXT NOT NULL,
  horizon TEXT NOT NULL,
  priority INTEGER NOT NULL,
  source TEXT,
  target_date TIMESTAMPTZ,
  importance_score DOUBLE PRECISION,
  urgency_score DOUBLE PRECISION,
  value_score DOUBLE PRECISION,
  effort_score DOUBLE PRECISION,
  risk_score DOUBLE PRECISION,
  alignment_score DOUBLE PRECISION,
  confidence_score DOUBLE PRECISION,
  expected_impact DOUBLE PRECISION,
  desired_outcomes JSONB NOT NULL DEFAULT '[]'::jsonb,
  success_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
  parent_goal_id TEXT,
  child_goal_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  milestone_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  active_plan_id TEXT,
  approval_mode TEXT,
  auto_decompose BOOLEAN NOT NULL DEFAULT FALSE,
  auto_schedule BOOLEAN NOT NULL DEFAULT FALSE,
  assumptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  policies JSONB NOT NULL DEFAULT '[]'::jsonb,
  constraints JSONB NOT NULL DEFAULT '[]'::jsonb,
  context JSONB,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  created_by TEXT NOT NULL,
  updated_by TEXT,
  audit_log JSONB NOT NULL DEFAULT '[]'::jsonb
);
