export * from './consent-manager';
export * from './audio-recorder';
export * from './intent-router';
export * from './stt';
export * from './whisper-adapter';
export * from './tts';
export * from './wake-word';
import { AudioRecorder, type AudioRecorderOptions } from './audio-recorder';
import { type ConsentManager } from './consent-manager';
import { IntentRouter, type IntentOutcome, type IntentRouterOptions, type VoiceEventPublisher } from './intent-router';
import { SpeechToText, type SpeechToTextOptions } from './stt';
import { TextToSpeech, type TextToSpeechOptions } from './tts';
import { WakeWordDetector, type WakeWordDetectorOptions } from './wake-word';
export interface VoiceCoreOptions {
    env?: NodeJS.ProcessEnv;
    graphPath?: string;
    armedTimeoutMs?: number;
    logger?: (message: string) => void;
    publish?: VoiceEventPublisher;
    now?: () => Date;
    router?: IntentRouter;
    routerOptions?: IntentRouterOptions;
    speechToText?: SpeechToText;
    speechToTextOptions?: SpeechToTextOptions;
    textToSpeech?: TextToSpeech;
    textToSpeechOptions?: TextToSpeechOptions;
    wakeWordDetector?: WakeWordDetector;
    wakeWordDetectorOptions?: WakeWordDetectorOptions;
    consentManager?: Pick<ConsentManager, 'hasConsent'>;
    audioRecorder?: AudioRecorder;
    audioRecorderOptions?: AudioRecorderOptions;
    captureWakeAudio?: boolean;
    wakeAudioSeconds?: number;
}
export declare class VoiceCore {
    private readonly detector;
    private readonly stt;
    private readonly router;
    private readonly tts;
    private readonly armedTimeoutMs;
    private readonly logger;
    private readonly publish;
    private readonly now;
    private readonly consentManager;
    private readonly audioRecorder;
    private readonly captureWakeAudio;
    private readonly wakeAudioSeconds;
    private capturingWakeCommand;
    private listeningUntil;
    private started;
    private closed;
    private wakeCaptureTask;
    constructor(options?: VoiceCoreOptions);
    getWakePhrase(): string;
    start(): Promise<void>;
    runDemo(text: string): Promise<IntentOutcome | null>;
    close(): Promise<void>;
    private processTranscript;
    private onWake;
    private processCommand;
    private speakSafely;
    private publishSafe;
}
export declare function createVoiceCore(options?: VoiceCoreOptions): VoiceCore;
